%% redraw_resnet50_conditional_control_2panel_v1.m
% Redraw-only manuscript figure for the pooled-nuisance ResNet-50
% conditional network control.
%
% This script does not rerun activations, PCA, k-means, or permutations.
% It reads the output tables generated by:
%   main_nn_entropic_compression_resnet50_controls_v4_FULL_FINAL.m
%
% Preferred input:
%   nn_resnet50_v4_controls_full_extended_all_seeds.csv
%
% Fallback input:
%   nn_resnet50_v4_controls_full_extended_main_table.csv
%
% Figure logic:
%   Panel A: full-scale view showing nuisance dominance.
%   Panel B: lower-range zoom showing object-related and conditional-object
%            information.
%
% Visual convention:
%   Points denote means across k-means initialisations.
%   Error bars denote bootstrap 95% confidence intervals across seeds when
%   all-seed rows are available. If only the summary table is available,
%   error bars denote mean +/- 1 SD across seeds.

clear; clc; close all;

cfg = struct();
cfg.projectRoot = 'I:\entropicCompression';
cfg.resultsDir  = fullfile(cfg.projectRoot, 'results');
cfg.figDir      = fullfile(cfg.projectRoot, 'figures');

cfg.analysisTag = 'mild_control'; %'full_extended'; %
cfg.mainK       = 10;
cfg.mainPcaDim  = 30;

cfg.allSeedsFile = fullfile(cfg.resultsDir, ...
    ['nn_resnet50_v4_controls_' cfg.analysisTag '_all_seeds.csv']);
cfg.mainFile = fullfile(cfg.resultsDir, ...
    ['nn_resnet50_v4_controls_' cfg.analysisTag '_main_table.csv']);

cfg.outBase = ['figure_nn_resnet50_v4_conditional_controls_' cfg.analysisTag '_2panel'];

cfg.layers = { ...
    'activation_4_relu',  ...
    'activation_7_relu',  ...
    'activation_10_relu', ...
    'activation_13_relu', ...
    'activation_16_relu', ...
    'activation_19_relu', ...
    'activation_22_relu', ...
    'activation_25_relu', ...
    'activation_28_relu', ...
    'activation_31_relu', ...
    'activation_34_relu', ...
    'activation_37_relu', ...
    'activation_40_relu', ...
    'activation_43_relu', ...
    'activation_46_relu', ...
    'activation_49_relu', ...
    'avg_pool'};

% Greyscale line settings.
cfg.colNuisance      = [0.65 0.65 0.65];
cfg.colCondObject  = [0.35 0.35 0.35];
cfg.colObject    = [0.05 0.05 0.05];
cfg.colCorrected   = [0.20 0.20 0.20];

cfg.lineObject      = '-';
cfg.lineCondObject  = ':';
cfg.lineNuisance    = '-';
cfg.lineCorrected   = '--';

cfg.markerObject      = 'none';
cfg.markerCondObject  = 'none';
cfg.markerNuisance    = 'none';
cfg.markerCorrected   = 'none';

cfg.lineWidthObject    = 1;
cfg.lineWidthCond      = 1;
cfg.lineWidthNuisance  = 1;
cfg.lineWidthCorrected = 1;

cfg.errWidth   = 0.75;
cfg.markerSize = 0.1;
cfg.capWidth   = 0.18;

cfg.nBoot = 2000;
cfg.rngSeed = 9101;

if ~exist(cfg.figDir, 'dir')
    mkdir(cfg.figDir);
end

T = load_and_summarise_control(cfg);
make_figure(cfg, T);

fprintf('\nConditional-control figure redrawn. No analysis rerun.\n');

%% ========================================================================
% Load and summarise
% ========================================================================
function S = load_and_summarise_control(cfg)

if exist(cfg.allSeedsFile, 'file')
    fprintf('Reading all-seed table:\n  %s\n', cfg.allSeedsFile);
    T = readtable(cfg.allSeedsFile, 'Delimiter', ',', 'PreserveVariableNames', true);

    T = T(T.k == cfg.mainK & T.pcaDim == cfg.mainPcaDim, :);
    if isempty(T)
        error('No rows found for k=%d and pcaDim=%d in all-seed table.', ...
            cfg.mainK, cfg.mainPcaDim);
    end

    S = summarise_from_seed_rows(T, cfg);

elseif exist(cfg.mainFile, 'file')
    fprintf('All-seed table not found. Reading main summary table:\n  %s\n', cfg.mainFile);
    M = readtable(cfg.mainFile, 'Delimiter', ',', 'PreserveVariableNames', true);

    M = M(M.k == cfg.mainK & M.pcaDim == cfg.mainPcaDim, :);
    if isempty(M)
        error('No rows found for k=%d and pcaDim=%d in main table.', ...
            cfg.mainK, cfg.mainPcaDim);
    end

    S = summarise_from_main_table(M, cfg);

else
    error(['Could not find either input table:\n  %s\nor\n  %s'], ...
        cfg.allSeedsFile, cfg.mainFile);
end

S = sort_by_layer(S, cfg.layers);

end

function S = summarise_from_seed_rows(T, cfg)

metrics = { ...
    'NMI_Yobj', ...
    'CNMI_Yobj_given_V', ...
    'NMI_V', ...
    'corr_CNMI_Yobj_given_V'};

layers = unique(string(T.layer), 'stable');

S = table();
rng(cfg.rngSeed, 'twister');

for iL = 1:numel(layers)
    idx = string(T.layer) == layers(iL);
    row = table();
    row.layer = layers(iL);
    row.k = cfg.mainK;
    row.pcaDim = cfg.mainPcaDim;
    row.nSeeds = sum(idx);

    for iM = 1:numel(metrics)
        m = metrics{iM};
        vals = T.(m)(idx);
        vals = vals(isfinite(vals));

        row.([m '_mean']) = mean(vals, 'omitnan');

        if numel(vals) >= 2
            bootMeans = nan(cfg.nBoot,1);
            n = numel(vals);
            for b = 1:cfg.nBoot
                bootMeans(b) = mean(vals(randi(n, n, 1)), 'omitnan');
            end
            row.([m '_ci_low'])  = prctile(bootMeans, 2.5);
            row.([m '_ci_high']) = prctile(bootMeans, 97.5);
        else
            row.([m '_ci_low'])  = row.([m '_mean']);
            row.([m '_ci_high']) = row.([m '_mean']);
        end
    end

    S = [S; row]; %#ok<AGROW>
end

end

function S = summarise_from_main_table(M, cfg)

metrics = { ...
    'NMI_Yobj', ...
    'CNMI_Yobj_given_V', ...
    'NMI_V', ...
    'corr_CNMI_Yobj_given_V'};

S = table();
S.layer = string(M.layer);
S.k = M.k;
S.pcaDim = M.pcaDim;

if any(strcmp(M.Properties.VariableNames, 'nSeeds'))
    S.nSeeds = M.nSeeds;
else
    S.nSeeds = nan(height(M),1);
end

for iM = 1:numel(metrics)
    m = metrics{iM};
    meanName = [m '_mean'];
    sdName   = [m '_sd'];

    if ~any(strcmp(M.Properties.VariableNames, meanName))
        error('Expected column not found in main table: %s', meanName);
    end

    S.(meanName) = M.(meanName);

    if any(strcmp(M.Properties.VariableNames, sdName))
        S.([m '_ci_low'])  = M.(meanName) - M.(sdName);
        S.([m '_ci_high']) = M.(meanName) + M.(sdName);
    else
        S.([m '_ci_low'])  = M.(meanName);
        S.([m '_ci_high']) = M.(meanName);
    end
end

end

function S = sort_by_layer(S, layers)

[tf, ord] = ismember(string(S.layer), string(layers));
if any(~tf)
    warning('Some layers in the table were not found in cfg.layers.');
end
[~, idx] = sort(ord);
S = S(idx,:);

end

%% ========================================================================
% Figure
% ========================================================================
function make_figure(cfg, T)

fig = figure('Color','w','Position',[80 80 750 330]);
tl = tiledlayout(fig, 1, 2, 'TileSpacing','compact', 'Padding','compact');

axA = nexttile(tl, 1);
plot_panel(axA, cfg, T, true);
title(axA, 'Full range', 'FontWeight','normal');

axB = nexttile(tl, 2);
plot_panel(axB, cfg, T, false);
title(axB, 'Object-related information', 'FontWeight','normal');

ax = [axA axB];

set(findall(fig, '-property', 'FontName'), 'FontName', 'Times New Roman');
set(findall(fig, '-property', 'FontSize'), 'FontSize', 9);

panelLabels = {'A','B'};
if exist('labelSubplots', 'file') == 2
    labelSubplots(ax, panelLabels, [0.15 0.004], false, ...
        'FontSize', 14, ...
        'FontName', 'Times New Roman', ...
        'FontWeight', 'normal');
else
    local_label_subplots(ax, panelLabels, [0.15 0.004], ...
        'FontSize', 14, ...
        'FontName', 'Times New Roman', ...
        'FontWeight', 'normal');
end

outPng = fullfile(cfg.figDir, [cfg.outBase '.png']);
outPdf = fullfile(cfg.figDir, [cfg.outBase '.pdf']);

print(fig, outPng, '-dpng', '-r300');
print(fig, outPdf, '-dpdf', '-bestfit');

fprintf('Saved figure:\n  %s\n  %s\n', outPng, outPdf);

end

function plot_panel(ax, cfg, T, includeNuisance)

hold(ax, 'on');
x = 1:height(T);

hObj = plot_metric(ax, x, T, ...
    'NMI_Yobj', ...
    cfg.colObject, cfg.lineObject, cfg.markerObject, ...
    cfg, 'Object NMI');

hCond = plot_metric(ax, x, T, ...
    'CNMI_Yobj_given_V', ...
    cfg.colCondObject, cfg.lineCondObject, cfg.markerCondObject, ...
    cfg, 'Object NMI | nuisance');

if includeNuisance
    hNui = plot_metric(ax, x, T, ...
        'NMI_V', ...
        cfg.colNuisance, cfg.lineNuisance, cfg.markerNuisance, ...
        cfg, 'Nuisance NMI');
else
    hNui = gobjects(0);
end

hCorr = plot_metric(ax, x, T, ...
    'corr_CNMI_Yobj_given_V', ...
    cfg.colCorrected, cfg.lineCorrected, cfg.markerCorrected, ...
    cfg, 'Corrected object NMI | nuisance');

format_layer_axis(ax, cfg.layers, height(T));

ylabel(ax, 'Normalised information');
xlabel(ax, 'Network layer');

if includeNuisance
    % Dynamic y-axis for Panel A: all plotted quantities, including nuisance.
    yMaxA = max([ ...
        T.NMI_Yobj_ci_high; ...
        T.CNMI_Yobj_given_V_ci_high; ...
        T.NMI_V_ci_high; ...
        T.corr_CNMI_Yobj_given_V_ci_high], [], 'omitnan');

    yTopA = ceil((yMaxA * 1.08) / 0.10) * 0.10;
    yTopA = max(0.10, min(1.05, yTopA));

    ylim(ax, [0 yTopA]);
    xlim(ax, [0 18]);
    ytA = linspace(0, yTopA, 5);
    set(ax, 'YTick', ytA, ...
        'YTickLabel', compose('%.2f', ytA));

    legend(ax, [hObj hCond hNui hCorr], ...
        {'Object NMI', ...
         'Object NMI | nuisance', ...
         'Nuisance NMI', ...
         'Corrected object NMI | nuisance'}, ...
        'Location','east', ...
        'Box','off');
else
    lowNames = { ...
        'NMI_Yobj_mean', ...
        'CNMI_Yobj_given_V_mean', ...
        'corr_CNMI_Yobj_given_V_mean'};
    mx = 0;
    for i = 1:numel(lowNames)
        mx = max(mx, max(T.(lowNames{i}), [], 'omitnan'));
    end

    % Dynamic y-axis for Panel B: object-related quantities only.
    yMinB = min([ ...
        T.NMI_Yobj_ci_low; ...
        T.CNMI_Yobj_given_V_ci_low; ...
        T.corr_CNMI_Yobj_given_V_ci_low], [], 'omitnan');

    yMaxB = max([ ...
        T.NMI_Yobj_ci_high; ...
        T.CNMI_Yobj_given_V_ci_high; ...
        T.corr_CNMI_Yobj_given_V_ci_high], [], 'omitnan');

    yLowB = floor((yMinB - 0.01) / 0.02) * 0.02;
    yTopB = ceil((yMaxB + 0.01) / 0.02) * 0.02;

    yLowB = max(0, yLowB);
    yTopB = max(yLowB + 0.04, yTopB);

    ylim(ax, [yLowB yTopB]);
    xlim(ax, [0 18]);
    ytB = linspace(yLowB, yTopB, 5);
    set(ax, 'YTick', ytB, ...
        'YTickLabel', compose('%.2f', ytB));
    
    legend(ax, [hObj hCond hCorr], ...
        {'Object NMI', ...
         'Object NMI | nuisance', ...
         'Corrected object NMI | nuisance'}, ...
        'Location','best', ...
        'Box','off');
end

end

function h = plot_metric(ax, x, T, metricBase, col, lineStyle, markerStyle, cfg, displayName)

y  = T.([metricBase '_mean']);
lo = T.([metricBase '_ci_low']);
hi = T.([metricBase '_ci_high']);

% Metric-specific line width.
switch metricBase
    case 'NMI_Yobj'
        lw = cfg.lineWidthObject;
    case 'CNMI_Yobj_given_V'
        lw = cfg.lineWidthCond;
    case 'NMI_V'
        lw = cfg.lineWidthNuisance;
    case 'corr_CNMI_Yobj_given_V'
        lw = cfg.lineWidthCorrected;
    otherwise
        lw = 1.15;
end

% Mean line only. No point markers.
h = plot(ax, x, y, ...
    'LineStyle', lineStyle, ...
    'Marker', markerStyle, ...
    'Color', col, ...
    'LineWidth', lw, ...
    'MarkerSize', cfg.markerSize, ...
    'DisplayName', displayName);

% Manual error bars only. No MATLAB errorbar function.
draw_manual_errorbars(ax, x, lo, hi, col, cfg.capWidth, cfg.errWidth);

end

function format_layer_axis(ax, layers, nRows)

layerLabels = clean_layer_labels(layers);
layerLabels = layerLabels(1:nRows);

set(ax, ...
    'XTick', 1:nRows, ...
    'XTickLabel', layerLabels, ...
    'XTickLabelRotation', 45, ...
    'TickLabelInterpreter','none', ...
    'Box','off', ...
    'TickDir','out', ...
    'FontName','Times New Roman', ...
    'FontSize',9, ...
    'LineWidth',0.75);

end

function labels = clean_layer_labels(layerNames)

labels = cellstr(string(layerNames));
for i = 1:numel(labels)
    labels{i} = strrep(labels{i}, 'activation_', 'act ');
    labels{i} = strrep(labels{i}, '_relu', ' relu');
    labels{i} = strrep(labels{i}, 'avg_pool', 'avg pool');
end

end

function local_label_subplots(ax, labels, offset, varargin)

for i = 1:numel(ax)
    if ~isgraphics(ax(i), 'axes')
        continue;
    end

    pos = get(ax(i), 'Position');
    x = pos(1) - offset(1) * pos(3);
    y = pos(2) + pos(4) + offset(2) * pos(4);

    annotation(gcf, 'textbox', [x y 0.03 0.03], ...
        'String', labels{i}, ...
        'LineStyle', 'none', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'bottom', ...
        varargin{:});
end

end

function draw_manual_errorbars(ax, x, yLow, yHigh, col, capWidth, lineWidth)

x     = x(:);
yLow  = yLow(:);
yHigh = yHigh(:);

for i = 1:numel(x)
    line(ax, [x(i) x(i)], [yLow(i) yHigh(i)], ...
        'Color', col, ...
        'LineWidth', lineWidth, ...
        'HandleVisibility', 'off');

    line(ax, [x(i)-capWidth/2 x(i)+capWidth/2], [yLow(i) yLow(i)], ...
        'Color', col, ...
        'LineWidth', lineWidth, ...
        'HandleVisibility', 'off');

    line(ax, [x(i)-capWidth/2 x(i)+capWidth/2], [yHigh(i) yHigh(i)], ...
        'Color', col, ...
        'LineWidth', lineWidth, ...
        'HandleVisibility', 'off');
end

end
