function drawManualBarLegend(ax, cols, labels, xAnchor, yAnchor, swW, swH, dy, fs)
% drawManualBarLegend
% Draw a compact manual legend for grouped bar plots.
%
% xAnchor, yAnchor are axes-normalised coordinates.
% swW and swH are swatch width and height in axes-relative units.
%
% This function uses annotation objects attached to the ancestor figure,
% so it works when ax is inside a tiledlayout.

    fig = ancestor(ax, 'figure');

    if isempty(fig) || ~isvalid(fig)
        error('drawManualBarLegend:InvalidFigure', ...
            'Could not find a valid ancestor figure for the supplied axes.');
    end

    oldUnits = ax.Units;
    ax.Units = 'normalized';
    axPos = ax.Position;
    ax.Units = oldUnits;

    for i = 1:numel(labels)

        x0 = axPos(1) + xAnchor * axPos(3);
        y0 = axPos(2) + (yAnchor - (i-1)*dy) * axPos(4);

        annotation(fig, 'rectangle', ...
            [x0, y0, swW*axPos(3), swH*axPos(4)], ...
            'FaceColor', cols(i,:), ...
            'EdgeColor', 'none');

        annotation(fig, 'textbox', ...
            [x0 + 1.25*swW*axPos(3), ...
             y0 - 0.012*axPos(4), ...
             0.75*axPos(3), ...
             0.055*axPos(4)], ...
            'String', labels{i}, ...
            'Interpreter', 'latex', ...
            'FontName', 'Times New Roman', ...
            'FontSize', fs, ...
            'LineStyle', 'none', ...
            'VerticalAlignment', 'middle', ...
            'HorizontalAlignment', 'left');
    end
end