function drawManualLineLegend(ax, cols, lineStyles, markers, labels, ...
    xAnchor, yAnchor, lineW, dy, fs)
% drawManualLineLegend
% Draw a compact manual legend for line plots.
%
% Coordinates xAnchor/yAnchor are in axes-relative coordinates.
% This works inside tiledlayout because all annotation objects are attached
% to the ancestor figure, not to ax.Parent.

    fig = ancestor(ax, 'figure');

    if isempty(fig) || ~isvalid(fig)
        error('drawManualLineLegend:InvalidFigure', ...
            'Could not find a valid ancestor figure for the supplied axes.');
    end

    oldUnits = ax.Units;
    ax.Units = 'normalized';
    axPos = ax.Position;
    ax.Units = oldUnits;

    for i = 1:numel(labels)

        x0 = axPos(1) + xAnchor * axPos(3);
        y0 = axPos(2) + (yAnchor - (i-1)*dy) * axPos(4);

        x1 = x0 + lineW * axPos(3);

        annotation(fig, 'line', ...
            [x0 x1], [y0 y0], ...
            'Color', cols(i,:), ...
            'LineStyle', lineStyles{i}, ...
            'LineWidth', 1);

        annotation(fig, 'textbox', ...
            [x1 + 0.035*axPos(3), ...
             y0 - 0.025*axPos(4), ...
             0.78*axPos(3), ...
             0.055*axPos(4)], ...
            'String', labels{i}, ...
            'Interpreter', 'none', ...
            'FontName', 'Times New Roman', ...
            'FontSize', fs, ...
            'LineStyle', 'none', ...
            'VerticalAlignment', 'middle', ...
            'HorizontalAlignment', 'left');
    end
end